version: 0.2

#env:
#variables:
    # key: "value"
    # key: "value"
#parameter-store:
    # key: "value"
    # key: "value"

phases:
  install:
    runtime-versions:
      nodejs: 10
  # commands:
    # - npm install
    # - command
  #finally:
    # - command
    # - command

#pre_build:
  #commands:
      # - npm install
    # - command
  #finally:
    # - command
    # - command
  build:
    commands:
      - npm install
      - npm run bundle
      - echo "VR-INFO ----- Build Done!"
    # - command
    # - command
  #finally:
    # - command
    # - command
  #post_build:
    #commands:
      #- mkdir build/static_assets/
      #- cp -R static_assets build/static_assets/
      #
  #finally:
    # - command
    # - command
artifacts:
  files:
    - build*/**
  # - location
  # - name
#discard-paths: yes
#base-directory: 'build/'
#cache:
  paths:
    - static_assets*/**
  # - path