version: 0.1

#env:
#variables:
    # key: "value"
    # key: "value"
#parameter-store:
    # key: "value"
    # key: "value"

phases:
  install:
    commands:
      - npm install
    # - command
  #finally:
    # - command
    # - command

#pre_build:
  #commands:
      # - npm install
    # - command
  #finally:
    # - command
    # - command
build:
  commands:
    - npm run bundle
    - echo "Build Done!"
    # - command
    # - command
  #finally:
    # - command
    # - command
#post_build:
  #commands:
    # - command
    # - command
  #finally:
    # - command
    # - command
artifacts:
    files:
      - '**/*'
  # - location
  # - name
#discard-paths: yes
base-directory: 'build/'
#cache:
#paths:
    # - .git
  # - path